spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/litemall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: nsl
      password: 1qaz@WSX
      initial-size: 10
      max-active: 20
      min-idle: 10
      max-wait: 10000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: true
      filters: stat,wall

mybatis:
  mapper-locations: classpath:mapper/*.xml